server:
  port: 0

spring:
  application:
    name: CafeInfo-Service

eureka:
  instance:
    instance-id: ${spring.application.name}.${random.value}
    
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka

pivotal:
  cafeinfoservice:
    name: CafeInfo-Service
  
  cafereviewservice:
    name: CafeReview-Service